# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('place', models.CharField(max_length=216)),
                ('plave_code', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('date_end', models.DateField(blank=True)),
                ('sponsor', models.CharField(blank=True, max_length=512)),
                ('organizer', models.CharField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modeified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('short', models.CharField(max_length=256)),
                ('sex', models.CharField(max_length=4)),
                ('order', models.CharField(max_length=4)),
                ('separator_1', models.CharField(max_length=4)),
                ('separator_2', models.CharField(max_length=4)),
                ('separator_3', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modeified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=64)),
                ('entry', models.BooleanField(default=False)),
                ('section', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modeified', models.DateTimeField(auto_now=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Comp')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Event')),
            ],
        ),
    ]
