# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventstatus',
            unique_together=set([('comp', 'event', 'section', 'match_round')]),
        ),
    ]
