# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='modeified',
            new_name='modified',
        ),
    ]
