# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20170428_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='plave_code',
            new_name='place_code',
        ),
    ]
