# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20170503_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_type',
            field=models.CharField(choices=[('Track8', 'トラック(セパレートスタート)'), ('TrackN', 'トラック(オープンレーンスタート)'), ('HJPV', '走高跳,棒高跳'), ('LJTJ', '走幅跳,三段跳'), ('Throw', '投擲競技')], default='Track8', max_length=8),
        ),
        migrations.AddField(
            model_name='event',
            name='wind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='section',
            field=models.CharField(choices=[('VS', '対校'), ('OP', 'OP'), ('Sub', '補欠'), ('TT', '記録会'), ('XX', 'その他')], default='OP', max_length=4),
        ),
    ]
