# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20170505_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_list_priority',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='start_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='wind',
            field=models.BooleanField(default=True),
        ),
    ]
