# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20170428_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='place',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='separator_1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='separator_2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='separator_3',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
