# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20170428_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='modeified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='eventstatus',
            old_name='modeified',
            new_name='modified',
        ),
    ]
