# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20170506_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='GR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(blank=True, max_length=6)),
                ('name_family', models.CharField(help_text='姓', max_length=64, verbose_name='family name')),
                ('name_first', models.CharField(help_text='名', max_length=64, verbose_name='first name')),
                ('club', models.CharField(blank=True, help_text='ex. 大阪大', max_length=256)),
                ('year', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Comp')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gr',
            unique_together=set([('comp', 'event')]),
        ),
    ]
