# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20170506_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='date_end',
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='start_list_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comp',
            name='status',
            field=models.CharField(choices=[('Entry', 'Entry'), ('StandBy', 'Stand By'), ('OnGoing', 'On Going'), ('Result', 'Result')], default='lock', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('W', '女'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='short',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='section',
            field=models.CharField(choices=[('VS', '対校'), ('OP', 'OP'), ('TT', '記録会'), ('XX', 'その他')], default='OP', max_length=4),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Entry', 'Entry'), ('StandBy', 'Stand By'), ('OnGoing', 'On Going'), ('Result', 'Result')], default='lock', max_length=16),
        ),
    ]
