# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20170508_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_list_priority',
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='start_list_priority',
            field=models.IntegerField(default=100000),
        ),
    ]
