# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20170428_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='status',
            field=models.CharField(choices=[('lock', 'Lock'), ('entry', 'Entry'), ('standby', 'Stand By'), ('result', 'Result')], default='lock', max_length=16),
        ),
    ]
