# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20170508_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_list_priority',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='start_list_priority',
            field=models.IntegerField(default=999999),
        ),
    ]
