# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='club',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
