# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20170601_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='geme_round',
            new_name='game_round',
        ),
    ]
