# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20170601_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('comp', 'event', 'game_class', 'game_round', 'bib')]),
        ),
    ]
