# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20170515_0150'),
        ('competitions', '0013_auto_20170601_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='event_status',
        ),
        migrations.AddField(
            model_name='result',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.Entry'),
        ),
    ]
