# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20170601_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='cardinal_organizer',
            field=models.BooleanField(default=False, verbose_name='競技会運営ツール使用'),
        ),
    ]
