# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bib', models.CharField(blank=True, max_length=64)),
                ('name_family', models.CharField(help_text='姓', max_length=64, verbose_name='family name')),
                ('name_first', models.CharField(help_text='名', max_length=64, verbose_name='first name')),
                ('kana_family', models.CharField(help_text='セイ', max_length=64)),
                ('kana_first', models.CharField(help_text='メイ', max_length=64)),
                ('sex', models.CharField(choices=[('M', '男'), ('W', '女'), ('F', '家族'), ('X', 'その他'), ('U', 'Unknown')], default='U', max_length=4)),
                ('grade', models.CharField(blank=True, help_text='ex. B4', max_length=64)),
                ('club', models.CharField(blank=True, help_text='ex. 大阪大', max_length=256)),
                ('jaaf_branch', models.CharField(max_length=64)),
                ('personal_best', models.CharField(blank=True, max_length=6)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('order_lane', models.CharField(blank=True, max_length=64)),
                ('entry_status', models.CharField(choices=[('Entry', 'Entry'), ('Entry_2', 'Entry_2'), ('stand_by', 'StandBy'), ('Finish', 'Finish'), ('DNS', 'DNS'), ('DNF', 'DNF'), ('DQ', 'DQ'), ('NM', 'NM'), ('NH', 'NH')], default='Entry', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.EventStatus')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('event_status', 'group', 'order_lane')]),
        ),
    ]
