# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='color_red',
            new_name='check',
        ),
    ]
