# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20170502_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order_lane',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
