# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20170515_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Entry_2', 'Entry_2'), ('stand_by', 'StandBy'), ('Result', 'Result'), ('DNS', 'DNS'), ('DNF', 'DNF'), ('DQ', 'DQ'), ('NM', 'NM'), ('NH', 'NH')], default='Entry', max_length=64),
        ),
    ]
